// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTAQzujTe2SL6_sSi2DdSIcsqgVs8weM',
    appId: '1:685159031566:web:fe86dd024903f935e02d5f',
    messagingSenderId: '685159031566',
    projectId: 'scientific-reasearch-discover',
    authDomain: 'scientific-reasearch-discover.firebaseapp.com',
    storageBucket: 'scientific-reasearch-discover.firebasestorage.app',
    measurementId: 'G-VZXTGL6CKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvI_JQQynDdIkkxM9gZI27JUrJRt3kuE',
    appId: '1:685159031566:android:9c2896fdb2f4bd27e02d5f',
    messagingSenderId: '685159031566',
    projectId: 'scientific-reasearch-discover',
    storageBucket: 'scientific-reasearch-discover.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLzwGU0XVBxhO6j4YHeyTlYrwzg7JiSc',
    appId: '1:685159031566:ios:b9066da107a9f672e02d5f',
    messagingSenderId: '685159031566',
    projectId: 'scientific-reasearch-discover',
    storageBucket: 'scientific-reasearch-discover.firebasestorage.app',
    iosBundleId: 'com.example.scientificResearchDiscover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyLzwGU0XVBxhO6j4YHeyTlYrwzg7JiSc',
    appId: '1:685159031566:ios:b9066da107a9f672e02d5f',
    messagingSenderId: '685159031566',
    projectId: 'scientific-reasearch-discover',
    storageBucket: 'scientific-reasearch-discover.firebasestorage.app',
    iosBundleId: 'com.example.scientificResearchDiscover',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjTAQzujTe2SL6_sSi2DdSIcsqgVs8weM',
    appId: '1:685159031566:web:dc43ef18539e0b2de02d5f',
    messagingSenderId: '685159031566',
    projectId: 'scientific-reasearch-discover',
    authDomain: 'scientific-reasearch-discover.firebaseapp.com',
    storageBucket: 'scientific-reasearch-discover.firebasestorage.app',
    measurementId: 'G-GWYNTTCXEZ',
  );
}
